/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721Koi__factory } from "./ERC721Koi__factory";
export { KoiCert__factory } from "./KoiCert__factory";
